### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by sghignone** [vipints/GFFtools-GX#2]
I'm trying to use gff_to_gtf.py to convert Potato genome v.4.03 annotation (http://solanaceae.plantbiology.msu.edu/pgsc_download.shtml; precisely, this file: http://solanaceae.plantbiology.msu.edu/data/PGSC_DM_V403_genes.gff.zip) in gft ,and I'm getting this:

> ~$ python scripts/GFFtools-GX/gff_to_gtf.py PGSC_DM_V403_genes.gff > PGSC_DM_V403_genes.gtf
> Traceback (most recent call last):
>   File "scripts/GFFtools-GX/gff_to_gtf.py", line 77, in <module>
>     Transcriptdb = GFFParser.Parse(gff_fname)  
>   File "/home/stefano/scripts/GFFtools-GX/GFFParser.py", line 130, in Parse
>     ftype, tags = attribute_tags(parts[-1])
>   File "/home/stefano/scripts/GFFtools-GX/GFFParser.py", line 61, in attribute_tags
>     key, val = item
> ValueError: too many values to unpack

what does it mean?
I just did git clone of the package; am I missing something ?
Thanks
s.

**Comment by vipints** [comment]
Looking into this.
